---
title: "1. Introduction to vimix"
author: "Alessandra Cabassi"
date: "`r Sys.Date()`"
output: 
    html_document:
      fig_width: 8
      theme: united
      toc: yes
vignette: >
  %\VignetteIndexEntry{1. Introduction to vimix}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r example1, message=FALSE, warning=FALSE, cache=TRUE}
library(mvtnorm)
library(vimix)

## Load a dataset containing 200 2-dimensional data points
data <- rbind(rmvnorm(100,c(-3,0)), rmvnorm(100,c(3,0)))

## Use variational inference for mixture of Gaussians to find clusters
output <- vimix(data, K = 7, verbose = T)
```

```{r example1-plot, fig.show='hold', message=FALSE, warning=FALSE, cache=TRUE}
## Plot cluster labels
library(ggplot2)
library(broom)
library(gridExtra)

## Convert data matrix and cluster labels to data.frame
df <- tidy(data)
df$label <- as.factor(output$label)

## Plot clusters
ggplot(df, aes(X1, X2, col = label)) + geom_point()
```

```{r example1-lb, fig.show='hold', message=FALSE, warning=FALSE, cache=TRUE}
## Check that the lower bound is monotonically increasing

lb <- tidy(output$L[-1])
lb$ELBO <- lb$x
lb$x <- NULL
lb$iter <- c(1:length(output$L[-1]))
lb$number_clusters <- output$Cl[-1]

## Plot lower bound
plot_lb <- ggplot(lb, aes(x=iter,y=ELBO)) + geom_line(linetype = "dashed") + geom_point()

## Plot number of non-empty clusters
plot_nc <- ggplot(lb, aes(x=iter,y=number_clusters)) + geom_line(linetype = "dashed") + geom_point()

grid.arrange(plot_lb, plot_nc, ncol = 2)
```

```{r example1-figure10-7, fig.show='hold', message=FALSE, warning = FALSE, cache=TRUE}
maxK <- 10
n_random_starts <- 100
ELBO <- matrix(0, maxK-1, n_random_starts)
for(k in 2:maxK){
    for(j in 1:n_random_starts){
        output <- vimix(data, K = k)
        ELBO[k-1,j] <- output$L[length(output$L)]
    }
}

library(reshape)
ELBO <- melt(t(ELBO))
names(ELBO) <- c('start_n', 'K', 'ELBO')
ELBO$K <- ELBO$K + 1

ggplot(ELBO, aes(x = K, y = ELBO)) + geom_point() + geom_jitter()
```

```{r example1-ind, message=FALSE, warning=FALSE, cache=TRUE}

## Use variational inference for mixture of Gaussians to find clusters
output <- vimix(data, K = 7, indep = T, verbose = T)
```

```{r example1-ind-plot, fig.show='hold', message=FALSE, warning=FALSE, cache=TRUE}
## Convert data matrix and cluster labels to data.frame
df <- tidy(data)
df$label <- as.factor(output$label)

## Plot clusters
ggplot(df, aes(X1, X2, col = label)) + geom_point()
```

```{r example1-ind-lb, fig.show='hold', message=FALSE, warning=FALSE, cache=TRUE}
## Check that the lower bound is monotonically increasing

lb <- tidy(output$L[-1])
lb$ELBO <- lb$x
lb$x <- NULL
lb$iter <- c(1:length(output$L[-1]))
lb$number_clusters <- output$Cl[-1]

## Plot clusters
plot_lc <- ggplot(lb, aes(x=iter,y=ELBO)) + geom_line(linetype = "dashed") + geom_point()

## Plot number of non-empty clusters
plot_nc <- ggplot(lb, aes(x=iter,y=number_clusters)) + geom_line(linetype = "dashed") + geom_point()

grid.arrange(plot_lb, plot_nc, ncol = 2)
```

```{r example1-ind-figure10-7, fig.show='hold', message=FALSE, warning = FALSE, cache=TRUE}
maxK <- 10
n_random_starts <- 100
ELBO <- matrix(0, maxK-1, n_random_starts)
for(k in 2:maxK){
    for(j in 1:n_random_starts){
        output <- vimix(data, K = k, indep = T)
        ELBO[k-1,j] <- output$L[length(output$L)]
    }
}

library(reshape)
ELBO <- melt(t(ELBO))
names(ELBO) <- c('start_n', 'K', 'ELBO')
ELBO$K <- ELBO$K + 1

ggplot(ELBO, aes(x = K, y = ELBO)) + geom_point() + geom_jitter()
```
